exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "org/*"]

# Dependencies

markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               YiStats
tagline:             'Reflection on a Life via Data Analytics'
description:         '“Life can only be understood backwards; but it must be lived forwards.” 
― Søren Kierkegaard '
# Thoughts about my life through data and statistical technics.'
url:                 http://yi-tang.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Yi Tang 
  url:               https://twitter.com/yi_stats
  email:             yi.tan.uk@me.com

# Custom vars
version:             1.0.0


# Includes an icon in the footer for each user name you enter
footer-links:
  github: yi-tang
  twitter: yi_stats
  linkedin: tonytangyi	   
