#+BEGIN_HTML
---
layout: post
title: weekly review - 49
excerpt: 
categories:
  -  
tags:
  - review, QS
---
#+END_HTML

Last week, I said I will start to 
1. track my time 60/24/7,
2. daily review on Stats Consultancy project
3. revise stats notes in Uni 

** Quantifised self 
I have been using [[http://dayoneapp.com][Day One]] to track my time when I was away from keyboard, most likely when I hangout with friends. An tracking journal would be like this:

#+begin_example
1132, start to write 
1432, shopping 
1510, chat with a friend 
1559, take a nap 
1626, wake, walk to a friend's house 
have dinner until 1832 
#+end_example

Then during the night, i would spent 10-30 minute to transfer org entries, I find this process is particularlly tedious, because for each entry, i need to 
1. clock in and out,
2. navigate to clock entry and change the time (and date sometimes) four times,
3. refile to entries to the right org file. 

I managed to write R scripts to prase the journal to org entries automatically, the main problems is typeiing on iPhone, and i decieded to go back to use aTimeLogger. I set-up the most frequency acitivities, like eat-breakfast, eat-lunch, ..., commute, sleep etc. All I need to do is press the coressponding bottom and it will begin to clock, and when it's done, i will write note few words. During the night, i will 
1. export today's entries to a CSV file, 
2. fire up R and load the CSV file, run a function, 
3. copy the output (complete org entries with clock entires) to a .org file and begin to refile. 
I am quit enjoy this workflow at this moment, it makes my life a lot esaier, and I also want to explore the possibliyf of automating the refile step. 

** New Habits 

For some reason, I fond myself not being distracted easier. This character noramlly is a good thing, but for me, it was to been a extrened that beging a really bad thing. I constantly found myself being trap in a technical problems for 2-3 hours, usually resulting in a unproductive morning or afternoon. 


I am a statistician, had a math degree and enjoy problem-solving. I have been working on many difficulty problem (not necessary for others but deifnitely for me) like teach myself Emacs/org-mode, R and C++11. Whenever I confront a problem, my brain is stimulate and i got excited, will dive in and be ready to fight to death. It is a character that I'm proud of. Sometimes, the problem was out of my reach, and i found myself being trapped there for 2-3 hours, sometimes even days, and can't get anything valueble out of it. 


I use org mode to help me to form a good habits: i will tell myself to stop and re-assess the problem if I've been working for then 90 minutes on a single tasks. The clocking time can be see very easiler in modeline. If that happen, i will start to write a report about 1) what's the problem, 2) what've done, 3) what's value solution. It will gives a time to claim down and writing it down in words really helps to undertand the problem deeper, and break down the problems into small tasks and seek for help. 

** Goals for next week 
1. life 
   - [ ] read mindfullness and collect good habits 
   - [ ] cook Lasania
   - [ ] watch The Hobbit: The Battle of the Five Armies
2. CPD
   - [ ] build my R package and host on Github
   - [ ] revise notes on blogging using org-mode and Jeykll 
   - [ ] orgnise study notes on Markov Chain Monte Carlo
3. Work 
   - [ ] do more R coaching 
   - [ ] keep practising project managing skill
   - [ ] keep practising oragnising skill



** Focus and time review
*Focus and time review* 
- Work
  - Coding (6h)
    - develop (5h)
    - coaching (1h)
  - Stats (11)
    - Apply HT model (5h)
    - Mote Carlo approxcimation with Ani-thetics variable (3h)
    - Applying Tower property (3h)
  - Report (11h)
    - write (5h)
    - edit (6h)
- Discretionary – Productive
  - [X] Emacs 
    - [X] managing org files 
    - [X] managing projects in org files 
  - [X] R 
    - [X] scripts that prase aTimeLogger data to org entries
  - [ ] Monte Carlo Simulation
    - [ ] Gibbs sampler 
  - [ ] Log quantifised-self data 
- Discretionary – Entertainment 
  - [ ] Watch The Imagination Game
  - [ ] Not Going Out
- Sleep (
- Bad habits (1.5h)
  - [ ] watch junk videos on youtube (1.5h)


